server:
  port: 8000 # 指定启动端口
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://xiaoheishu-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 127.0.0.1 # Redis 服务器地址
      port: 6379 # Redis 服务器端口
      password: 123321 # Redis 服务器密码
      timeout: 5s # 连接超时时间
      lettuce:
        pool:
          max-wait: -1ms # 连接池最大等待时间（负值表示无限制）
          max-active: 200 # 连接池最大连接数（负值表示无限制）
          min-idle: 0 # 连接池最小空闲连接
          max-idle: 10 # 连接池最大空闲连接
sa-token:
  # token名称 同时也是cookie名称
  token-name: Authorization
  # token 前缀
  token-prefix: Bearer
  # token的有效期（单位：秒）默认30天，-1代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果token超过这个时间没有访问系统就会被冻结，默认 -1 代表不限制，永久不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录，为 false 时挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用同一 token （为 false 时每登录一次就创建一个新的token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true