server:
  port: 8080


spring:
  profiles:
    active: dev

mybatis:
  # Mybatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

sa-token:
  # token名称 同时也是cookie名称
  token-name: Authorization
  # token 前缀
  token-prefix: Bearer
  # token的有效期（单位：秒）默认30天，-1代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果token超过这个时间没有访问系统就会被冻结，默认 -1 代表不限制，永久不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录，为 false 时挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用同一 token （为 false 时每登录一次就创建一个新的token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true

alarm:
  type: sms # 告警类型

rate-limit:
  api:
    limit: 100 # 接口限流阈值

#nacos:
#  config: # nacos 配置中心
#    access-key: # 身份验证
#    secret-key: # 身份验证
#    data-id: xiaoheishu-auth # 指定要加载的配置数据的 DATA ID
#    group: DEFAULT_GROUP # 指定配置数据所属的组
#    type: yaml # 配置格式
#    server-addr: http://127.0.0.1:8848/ # 指定 Nacos 服务中心的服务器地址
#    auto-refresh: true # 是否自动刷新配置
#    remote-first: true # 是否优先使用远程配置
#    bootstrap:
#      enable: true # 启动时，预热配置
